---
title: Neidio o'r brig i lawr
hero_image: images/banner.png
description: Gwneud i gymeriad neidio drwy symud a newid ei faint mewn gêm neu animeiddiad o'r brig i lawr.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Neidio o'r brig i lawr

