---
title: Salto de cima para baixo
hero_image: images/banner.png
description: Faça um personagem pular movendo e alterando o tamanho em um jogo ou animação de cima para baixo.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Salto de cima para baixo

