---
title: Top-down jumping
hero_image: images/banner.png
description: Make a character jump by moving and changing size in a top-down game or animation.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Top-down jumping

