---
title: Skakanie w widoku z góry
hero_image: images/banner.png
description: Spraw by postać skakała, poprzez poruszanie się i zmienianie rozmiaru w grze lub animacji z widokiem z góry.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Skakanie w widoku z góry

