---
title: Salti dall'alto
hero_image: images/banner.png
description: Fai saltare un personaggio, facendolo muovere e variando le sue dimensioni in un gioco o un'animazione con visuale dall'alto.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Salti dall'alto

